---
- block:

  - name: "Create [ {{ item }} ] VM with Template`"
    vmware_guest:
      hostname: '{{ vmware_name }}'
      username: '{{ vmware_user }}'
      password: '{{ vmware_pass }}'
      validate_certs: False
      name: '{{ item }}'
      datacenter: ha-datacenter
      folder: vm
      state: poweredon
      template: '{{ vmware_template }}'
      wait_for_ip_address: yes
    register: deploy

  - name: "Update Ansible hosts file with [ {{ item }} ] IP address"
    lineinfile:
      path: /etc/ansible/hosts
      insertafter: ^[test_group]
      line: "{{ deploy.instance.ipv4 }}"

  delegate_to: localhost
  tags: create_from_template
