---
- block:

  - name: "Creating [ {{ item }} ] VM with ISO"
    vmware_guest:
      hostname: '{{ vmware_host }}'
      username: '{{ vmware_user }}'
      password: '{{ vmware_pass }}'
      validate_certs: False
      name: '{{ item }}'
      datacenter: '{{ vmware_datacenter }}'
      folder: '{{ vmware_folder }}'
      state: poweredon
      guest_id: rhel7_64Guest
      disk:
      - size_gb: 100
        type: thin
        datastore: '{{ vmware_datastore }}'
      networks:
      - name: 'Server-LAN-10.10.10.0/24'
        device_type: vmxnet3
      hardware:
         memory_mb: 2048
         num_cpus: 2
         scsi: paravirtual
      cdrom:
         type: "iso"
         iso_path: "[datastore1] ISOs/rhel-server-7.7-x86_64-dvd.iso"
      wait_for_ip_address: yes
    register: deploy

  - name: "Update Ansible hosts file with [ {{ item }} ] IP address"
    lineinfile:
      path: /etc/ansible/hosts
      insertafter: ^[test_group]
      line: "{{ deploy.instance.ipv4 }}"

  delegate_to: localhost
  tags: create_new
