---
- block:

  - name: "Creating [ {{ item }} ] VM from OVF Template"
    vmware_deploy_ovf:
      hostname: '{{ vmware_host }}'
      username: '{{ vmware_user }}'
      password: '{{ vmware_pass }}'
      validate_certs: False
      name: '{{ item }}'
      ovf: '{{ vmware_ovf }}'
      datacenter: '{{ vmware_datacenter }}'
      folder: '/{{ vmware_datacenter }}/{{ vmware_folder }}'
      disk_provisioning: thin
      datastore: '{{ vmware_datastore }}'
      networks:
        'Server-LAN-10.10.10.0/24': 'Server-LAN-10.10.10.0/24'
      wait_for_ip_address: yes
    register: deploy

  - name: "Update Ansible hosts file with [ {{ item }} ] IP address"
    lineinfile:
      path: /etc/ansible/hosts
      insertafter: ^[test_group]
      line: "{{ deploy.instance.ipv4 }}"

  delegate_to: localhost
  tags: create_from_ovf
