---
- block:

  - name: "Gather [ {{ item }} ] Info"
    vmware_guest_info:
      hostname: '{{ vmware_host }}'
      username: '{{ vmware_user }}'
      password: '{{ vmware_pass }}'
      validate_certs: False
      name: '{{ item }}'
      datacenter: '{{ vmware_datacenter }}'
      folder: '{{ vmware_folder }}'
    register: vm_info

  - name: "Clean Ansible Hosts File of [ {{ item }} ] IP Address"
    lineinfile:
      path: /etc/ansible/hosts
      regexp: '{{ vm_info.instance.ipv4 }}'
      state: absent

  - name: "Powering Off the [ {{ item }} ] VM"
    vmware_guest:
      hostname: '{{ vmware_host }}'
      username: '{{ vmware_user }}'
      password: '{{ vmware_pass }}'
      validate_certs: False
      name: '{{ item }}'
      datacenter: '{{ vmware_datacenter }}'
      folder: '{{ vmware_folder }}'
      state: poweredoff

  - name: "Deleteing the [ {{ item }} ] VM"
    vmware_guest:
      hostname: '{{ vmware_host }}'
      username: '{{ vmware_user }}'
      password: '{{ vmware_pass }}'
      validate_certs: False
      name: '{{ item }}'
      datacenter: '{{ vmware_datacenter }}'
      folder: '{{ vmware_folder }}'
      state: absent

  delegate_to: localhost
  tags: delete
