---
- include_tasks: create_new.yml
  loop: '{{ guest_name }}'
  tags: create_new

- include_tasks: create_from_ovf.yml
  loop: '{{ guest_name }}'
  tags: create_from_ovf

- include_tasks: create_from_template.yml
  loop: '{{ guest_name }}'
  tags: create_from_template

- include_tasks: snapshot.yml
  loop: '{{ guest_name }}'
  tags: snapshot

- include_tasks: delete.yml
  loop: '{{ guest_name }}'
  tags: delete
